apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: demo-certificate
spec:
  domains:
    - www.arakey.dev
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: demo
  annotations:
    networking.gke.io/address-name: "my-website-gateway-ip"  # 作成した静的IPの名前を指定
    networking.gke.io/ssl-certificates: "demo-certificate"
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: Same

---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: demo-service
spec:
  parentRefs:
  - name: demo
    sectionName: https  # HTTPSリスナーも参照
  hostnames:
  - "www.arakey.dev"
  rules:
  - backendRefs:
    - name: demo-service # Service名
      port: 443
