apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: demo-certificate
spec:
  domains:
    - www.arakey.dev
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: demo-service
  annotations:
    networking.gke.io/address-name: "my-website-gateway-ip"  # 作成した静的IPの名前を指定
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  gatewayClassName: gke-l7-external-managed
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: Same

---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: demo-service
  annotations:
    external-dns.alpha.kubernetes.io/ttl: "30"
spec:
  parentRefs:
    - kind: Gateway
      name: demo-service
      namespace: demo-service
  hostnames:
  - "www.arakey.dev"
  rules:
  - matches:
      - path:
          type: PathPrefix
          value: /
    backendRefs:
      - name: demo-service # Service名
        port: 80
