apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: demo
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same

---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: demo-service
spec:
  parentRefs:
  - name: demo
  hostnames:
  - "www.arakey.dev"
  rules:
  - backendRefs:
    - name: demo-service # Service名
      port: 80    # HTTPポート
