import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="ja"
		>
			<body className={"antialiased font-noto-sans-jp"}>
				<main className="min-h-screen min-w-screen">{children}</main>
			</body>
		</html>
	);
}
